version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: playaxhata-app
        container_name: playaxhata-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - custom-export-network
        ports:
            - "9001:9000"
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: playaxhata
            DB_USERNAME: playaxhata
            DB_PASSWORD: playaxhata

    webserver:
        image: nginx:alpine
        container_name: playaxhata-webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - custom-export-network

    mysql:
        image: mysql:latest
        container_name: playaxhata-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootPassword
            MYSQL_DATABASE: playaxhata
            MYSQL_USER: playaxhata
            MYSQL_PASSWORD: playaxhata
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - custom-export-network

networks:
    custom-export-network:
        driver: bridge

volumes:
    mysql-data:
